replicaCount: 1

image:
  repository: accounts-service
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8083

container:
  port: 8083

keycloak:
  issuerUri: http://172.18.0.1:8080/realms/bank-realm

notifications:
  baseUrl: http://bank-app-notifications-service:8087

postgres:
  jdbcUrl: jdbc:postgresql://bank-app-postgres:5432/bank-app?currentSchema=accounts
  username: user
  password: sa

oauth:
  clientId: accounts-service
  clientSecret: accounts-service-secret