CREATE SCHEMA IF NOT EXISTS accounts;

CREATE TABLE IF NOT EXISTS accounts.accounts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login           VARCHAR(255) NOT NULL UNIQUE,
    first_last_name VARCHAR(255) NOT NULL,
    birth_date      DATE         NOT NULL,
    sum             NUMERIC(10, 2)
);