apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-accounts-service
data:
  application.yaml: |
    server:
      port: {{ .Values.container.port }}
    spring:
      application:
        name: accounts-service
      datasource:
        url: {{ .Values.postgres.jdbcUrl }}
        username: {{ .Values.postgres.username }}
      jpa:
        defer-datasource-initialization: true
      sql:
        init:
          mode: never
          schema-locations: classpath:schema.sql
          data-locations: classpath:data.sql
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.keycloak.issuerUri }}
          client:
            registration:
              accounts-service:
                client-id: {{ .Values.oauth.clientId }}
                authorization-grant-type: client_credentials
                provider: keycloak
            provider:
              keycloak:
                issuer-uri: {{ .Values.keycloak.issuerUri }}
      kafka:
        bootstrap-servers: bank-app-kafka-headless.default.svc.cluster.local:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bank:
      kafka:
        topic: notifications