apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cash-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cash-service
  template:
    metadata:
      labels:
        app: cash-service
    spec:
      containers:
        - name: cash-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: optional:file:/config/
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-cash-service
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: app-config
          configMap:
            name: {{ .Release.Name }}-cash-service