apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cash-service
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CASH_SERVICE_CLIENT_SECRET: {{ .Values.oauth.cashClientSecret | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_SERVICE_CLIENT_SECRET: {{ .Values.oauth.accountsClientSecret | quote }}