replicaCount: 1

image:
  repository: cash-service
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8085

container:
  port: 8085

keycloak:
  issuerUri: http://172.18.0.1:8080/realms/bank-realm

accounts:
  baseUrl: http://bank-app-accounts-service:8083

notifications:
  baseUrl: http://bank-app-notifications-service:8087

oauth:
  cashClientId: cash-service
  cashClientSecret: cash-service-secret
  accountsClientId: accounts-service
  accountsClientSecret: accounts-service-secret