apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bank-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bank-gateway
  template:
    metadata:
      labels:
        app: bank-gateway
    spec:
      containers:
        - name: bank-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-bank-gateway
            - secretRef:
                name: {{ .Release.Name }}-bank-gateway