apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-bank-gateway
type: Opaque
stringData:
  ACCOUNTS_SERVICE_CLIENT_SECRET: {{ .Values.oauth.accountsServiceClientSecret | quote }}
  CASH_SERVICE_CLIENT_SECRET: {{ .Values.oauth.cashServiceClientSecret | quote }}
  TRANSFER_SERVICE_CLIENT_SECRET: {{ .Values.oauth.transferServiceClientSecret | quote }}