apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-bank-ui
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: {{ .Values.oauth.keycloakClientSecret | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_SERVICE_CLIENT_SECRET: {{ .Values.oauth.accountsServiceClientSecret | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CASH_SERVICE_CLIENT_SECRET: {{ .Values.oauth.cashServiceClientSecret | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_CLIENT_SECRET: {{ .Values.oauth.transferServiceClientSecret | quote }}