observability:
  zipkinEndpoint: http://172.18.0.1:9411/api/v2/spans
  logstashHost: 172.18.0.1
  logstashPort: 5000

replicaCount: 1

image:
  repository: notifications-service
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8087

container:
  port: 8087

resources:
  requests:
    memory: 192Mi
    cpu: 100m
  limits:
    memory: 384Mi
    cpu: 300m

keycloak:
  issuerUri: http://172.18.0.1:8080/realms/bank-realm

kafka:
  topic: notifications
  consumerGroup: notifications-service