spring:
  application:
    name: bank-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts-service
              uri: ${ROUTES_ACCOUNTS_URI}
              predicates:
                - Path=/accounts/**
            - id: cash-service
              uri: ${ROUTES_CASH_URI}
              predicates:
                - Path=/cash/**
            - id: transfer-service
              uri: ${ROUTES_TRANSFER_URI}
              predicates:
                - Path=/transfer/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://172.18.0.1:8080/realms/bank-realm}

server:
  port: ${SERVER_PORT:8081}