server:
  port: 8083

bank:
  notifications:
    base-url: http://localhost:8087

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO

spring:
  config:
    import: "optional:consul:"
  application:
    name: accounts-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
      config:
        enabled: true
        format: yaml
        prefixes:
          - config
        default-context: application
        fail-fast: false
        watch:
          enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm
      client:
        registration:
          accounts-service:
            client-id: accounts-service
            client-secret: accounts-service-secret
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm

  datasource:
    url: jdbc:postgresql://localhost:5434/bank-app?currentSchema=accounts
    username: user
    password: sa

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

resilience4j:
  retry:
    instances:
      notificationsClient:
        maxAttempts: 3
        waitDuration: 500ms
  circuitbreaker:
    instances:
      notificationsClient:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
