server:
  port: 8086

bank:
  accounts:
    base-url: http://localhost:8083
  notifications:
    base-url: http://localhost:8087

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO

spring:
  config:
    import: "optional:consul:"
  application:
    name: transfer-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
      config:
        enabled: true
        format: yaml
        prefixes:
          - config
        default-context: application
        fail-fast: false
        watch:
          enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm
      client:
        registration:
          keycloak:
            client-id: transfer-service
            client-secret: transfer-service-secret
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak
          cash-service:
            client-id: transfer-service
            client-secret: transfer-service-secret
            authorization-grant-type: client_credentials
            provider: keycloak
          accounts-service:
            client-id: accounts-service
            client-secret: accounts-service-secret
            authorization-grant-type: client_credentials
            provider: keycloak
          transfer-service:
            client-id: transfer-service
            client-secret: transfer-service-secret
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm

resilience4j:
  retry:
    instances:
      notificationsClient:
        maxAttempts: 3
        waitDuration: 500ms
  circuitbreaker:
    instances:
      accountsClient:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      notificationsClient:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
