server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO

spring:
  application:
    name: accounts-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm

  datasource:
    url: jdbc:postgresql://localhost:5434/bank-app?currentSchema=accounts
    username: user
    password: sa

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql