observability:
  zipkinEndpoint: http://172.18.0.1:9411/api/v2/spans
  logstashHost: 172.18.0.1
  logstashPort: 5000

replicaCount: 1

image:
  repository: bank-ui
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 8084
  nodePort: 30277

container:
  port: 8084

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 512Mi
    cpu: 500m

keycloak:
  issuerUri: http://172.18.0.1:8080/realms/bank-realm

gateway:
  baseUrl: http://bank-app-bank-gateway:8081

oauth:
  keycloakClientSecret: ui-client-secret
  accountsServiceClientSecret: accounts-service-secret
  cashServiceClientSecret: cash-service-secret
  transferServiceClientSecret: transfer-service-secret