apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-transfer-service
data:
  application.yaml: |
    server:
      port: {{ .Values.container.port }}
    spring:
      application:
        name: transfer-service
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.keycloak.issuerUri }}
          client:
            registration:
              transfer-service:
                client-id: {{ .Values.oauth.clientId }}
                authorization-grant-type: client_credentials
                provider: keycloak
            provider:
              keycloak:
                issuer-uri: {{ .Values.keycloak.issuerUri }}
      kafka:
        bootstrap-servers: bank-app-kafka-headless.default.svc.cluster.local:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bank:
      accounts:
        base-url: {{ .Values.accounts.baseUrl }}
      kafka:
        topic: notifications