apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-transfer-service
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_TRANSFER_SERVICE_CLIENT_SECRET: {{ .Values.oauth.clientSecret | quote }}