apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-transfer-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: transfer-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}